image:
  name: dinov2
  checkpoint: dinov2_vitb14
  pooling: cls
caption:
  name: roberta
  checkpoint: roberta-base
  pooling: cls
alignment:
  name: clip_aligner
  vision_layer:
    - {"name": "mlp", "output": 768, "activation": "tanh"}
    - {"name": "mlp", "output": 768, "activation": ""}
  caption_layer:
    - {"name": "mlp", "output": 768, "activation": "tanh"}
    - {"name": "mlp", "output": 768, "activation": ""}