defaults:
  - model: clip_aligner
  - dataset: cc3m
  - loss: clip
  - override hydra/job_logging: disabled
  # - hydra/hydra_logging: disabled
  - _self_

log_file: "logs"
log_level: "INFO"
vis_logger: True
verbose: true
seed: 1998
compile: False
finetune: "heads"
batch_size: 64
num_workers: 4
batch_freq_print: 5
optimizer:
  _target_: torch.optim.AdamW
  lr: 5.0e-4
  weight_decay: 0.2
  betas: [0.9, 0.98]
  eps: 1.0e-6
scheduler:
  name: cosine_lr
  warmup_length: 0
epochs: 5
save_dir: "checkpoints"
save_period: 1
checkpoint: null
calculate_metrics: ["clip_loss", "image_to_text", "text_to_image"]

fabric:
  accelerator: "auto"
  devices: "auto"
  strategy: "auto"
  precision: null